# Generated by Django 3.1.2 on 2020-10-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20190919_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
