# Generated by Django 3.1.2 on 2020-10-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20201028_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmembership',
            old_name='field_name',
            new_name='email_id',
        ),
    ]
