# Generated by Django 3.1.2 on 2020-11-04 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201104_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
