# Generated by Django 3.1.2 on 2020-10-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190918_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allowed_memberships',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
