# Generated by Django 3.1.2 on 2020-10-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201028_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Branch_of_study',
        ),
        migrations.RenameField(
            model_name='branch_of_study',
            old_name='category',
            new_name='branch_of_study',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='branch_of_study',
        ),
    ]
